;;;###autoload
(defun ff/stack-overflow ()
  (interactive)
  (let ((buffer (current-buffer)))
    (switch-to-buffer "*stack-overflow*")
    (toggle-read-only 0)
    (delete-region (point-min) (point-max))
    (insert-buffer-substring buffer)
    (insert "    ")
    (while (= (forward-line) 0)
      (insert "    "))
    (toggle-read-only 1)))