;;;###autoload
(defun ff/stack-overflow ()
  (interactive)
  (let ((buffer (current-buffer)))
    (switch-to-buffer "*stack-overflow*")
    (toggle-read-only 0)
    (delete-region (point-min) (point-max))
    (insert-buffer-substring buffer)
    (indent-rigidly (point-min) (point-max) 4)
    (toggle-read-only 1)))