;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        LaTeX-babel-insert-hyphen
        LaTeX-insert-left-brace
        TeX-insert-backslash
        TeX-insert-dollar
        TeX-insert-sub-or-superscript
        autopair-insert-opening
        autopair-insert-or-skip-paired-delimiter
        autopair-insert-or-skip-quote
        autopair-skip-close-maybe
        c-electric-slash
        c-electric-star
        electric-newline-and-maybe-indent
        ff/insert-tilde
        ff/move-beginning-of-line
        ff/undo
        indent-for-tab-command
        join-line/repeat
        kill-region
        markdown-outdent-or-delete
        org-self-insert-command
        orgstruct-hijacker-org-cycle-4
        paredit-forward-delete
        paredit-newline
        paredit-open-round
        sexp-hydra/paredit-or-forward-sexp
        sh-assignment
        wdired-finish-edit
        wdired-next-line
        ))

(setq mc/cmds-to-run-once
      '(
        read-only-mode
        smex
        ))
