(defun ff/stack-overflow ()
  (interactive)
  (let ((buffer (current-buffer)))
    (switch-to-buffer "*stack-overflow*")
    (toggle-read-only 0)
    (erase-buffer)
    (insert-buffer buffer)
    (insert "    ")
    (while (= (forward-line) 0)
      (insert "    "))
    (toggle-read-only 1)))